{
 "title": "Capitan",
 "description": "ToC Machine Trading",
 "tags": [ "TBT" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-100*(node_memory_MemAvailable_bytes{job=\"node-exporter\"}/node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"capitan\"}[5m])*1000)",
     "legendFormat": "Capitan"
    },
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"postgres-exporter\"}[5m])*1000)",
     "legendFormat": "Postgres"
    },
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"titan\"}[5m])*1000)",
     "legendFormat": "Titan"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{job=\"postgres-exporter\"}[5m]))+sum(irate(pg_stat_database_xact_rollback{job=\"postgres-exporter\"}[5m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{job=\"postgres-exporter\"}[5m]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_returned{job=\"postgres-exporter\"}[5m]))",
     "legendFormat": "returned"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{job=\"postgres-exporter\"}[5m]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{job=\"postgres-exporter\"}[5m]))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{job=\"postgres-exporter\"}[5m]))",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"capitan\"}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"capitan\"}",
     "legendFormat": "Capittan"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"postgres-exporter\"}",
     "legendFormat": "Postgres"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"titan\"}",
     "legendFormat": "Titan"
    }
   ]
  }
 ]
}