// Code generated by MockGen. DO NOT EDIT.
// Source: basic_postgres.go
//
// Generated by this command:
//
//	mockgen -source=basic_postgres.go -destination=./mocks/mocks_basic_postgres_test.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pb "github.com/chindada/panther/golang/pb"
	gomock "go.uber.org/mock/gomock"
)

// MockBasicRepo is a mock of BasicRepo interface.
type MockBasicRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBasicRepoMockRecorder
	isgomock struct{}
}

// MockBasicRepoMockRecorder is the mock recorder for MockBasicRepo.
type MockBasicRepoMockRecorder struct {
	mock *MockBasicRepo
}

// NewMockBasicRepo creates a new mock instance.
func NewMockBasicRepo(ctrl *gomock.Controller) *MockBasicRepo {
	mock := &MockBasicRepo{ctrl: ctrl}
	mock.recorder = &MockBasicRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicRepo) EXPECT() *MockBasicRepoMockRecorder {
	return m.recorder
}

// DeleteFutureContract mocks base method.
func (m *MockBasicRepo) DeleteFutureContract(ctx context.Context, id []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFutureContract", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFutureContract indicates an expected call of DeleteFutureContract.
func (mr *MockBasicRepoMockRecorder) DeleteFutureContract(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFutureContract", reflect.TypeOf((*MockBasicRepo)(nil).DeleteFutureContract), ctx, id)
}

// InsertFutureContract mocks base method.
func (m *MockBasicRepo) InsertFutureContract(ctx context.Context, t *pb.FutureContract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFutureContract", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertFutureContract indicates an expected call of InsertFutureContract.
func (mr *MockBasicRepoMockRecorder) InsertFutureContract(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFutureContract", reflect.TypeOf((*MockBasicRepo)(nil).InsertFutureContract), ctx, t)
}

// InsertFutureDetail mocks base method.
func (m *MockBasicRepo) InsertFutureDetail(ctx context.Context, t []*pb.FutureDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFutureDetail", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertFutureDetail indicates an expected call of InsertFutureDetail.
func (mr *MockBasicRepoMockRecorder) InsertFutureDetail(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFutureDetail", reflect.TypeOf((*MockBasicRepo)(nil).InsertFutureDetail), ctx, t)
}

// InsertOptionDetail mocks base method.
func (m *MockBasicRepo) InsertOptionDetail(ctx context.Context, t []*pb.OptionDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOptionDetail", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOptionDetail indicates an expected call of InsertOptionDetail.
func (mr *MockBasicRepoMockRecorder) InsertOptionDetail(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOptionDetail", reflect.TypeOf((*MockBasicRepo)(nil).InsertOptionDetail), ctx, t)
}

// InsertStockDetail mocks base method.
func (m *MockBasicRepo) InsertStockDetail(ctx context.Context, t []*pb.StockDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStockDetail", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStockDetail indicates an expected call of InsertStockDetail.
func (mr *MockBasicRepoMockRecorder) InsertStockDetail(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStockDetail", reflect.TypeOf((*MockBasicRepo)(nil).InsertStockDetail), ctx, t)
}

// SearchFutureDetail mocks base method.
func (m *MockBasicRepo) SearchFutureDetail(ctx context.Context, code string) ([]*pb.FutureDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFutureDetail", ctx, code)
	ret0, _ := ret[0].([]*pb.FutureDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFutureDetail indicates an expected call of SearchFutureDetail.
func (mr *MockBasicRepoMockRecorder) SearchFutureDetail(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFutureDetail", reflect.TypeOf((*MockBasicRepo)(nil).SearchFutureDetail), ctx, code)
}

// SelectAllFutureContract mocks base method.
func (m *MockBasicRepo) SelectAllFutureContract(ctx context.Context) ([]*pb.FutureContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllFutureContract", ctx)
	ret0, _ := ret[0].([]*pb.FutureContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllFutureContract indicates an expected call of SelectAllFutureContract.
func (mr *MockBasicRepoMockRecorder) SelectAllFutureContract(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllFutureContract", reflect.TypeOf((*MockBasicRepo)(nil).SelectAllFutureContract), ctx)
}

// SelectAllFutureDetail mocks base method.
func (m *MockBasicRepo) SelectAllFutureDetail(ctx context.Context) ([]*pb.FutureDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllFutureDetail", ctx)
	ret0, _ := ret[0].([]*pb.FutureDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllFutureDetail indicates an expected call of SelectAllFutureDetail.
func (mr *MockBasicRepoMockRecorder) SelectAllFutureDetail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllFutureDetail", reflect.TypeOf((*MockBasicRepo)(nil).SelectAllFutureDetail), ctx)
}

// SelectAllOptionDetail mocks base method.
func (m *MockBasicRepo) SelectAllOptionDetail(ctx context.Context) ([]*pb.OptionDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllOptionDetail", ctx)
	ret0, _ := ret[0].([]*pb.OptionDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllOptionDetail indicates an expected call of SelectAllOptionDetail.
func (mr *MockBasicRepoMockRecorder) SelectAllOptionDetail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllOptionDetail", reflect.TypeOf((*MockBasicRepo)(nil).SelectAllOptionDetail), ctx)
}

// SelectAllStockDetail mocks base method.
func (m *MockBasicRepo) SelectAllStockDetail(ctx context.Context) ([]*pb.StockDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllStockDetail", ctx)
	ret0, _ := ret[0].([]*pb.StockDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllStockDetail indicates an expected call of SelectAllStockDetail.
func (mr *MockBasicRepoMockRecorder) SelectAllStockDetail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllStockDetail", reflect.TypeOf((*MockBasicRepo)(nil).SelectAllStockDetail), ctx)
}

// SelectFutureContractByID mocks base method.
func (m *MockBasicRepo) SelectFutureContractByID(ctx context.Context, id int64) (*pb.FutureContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFutureContractByID", ctx, id)
	ret0, _ := ret[0].(*pb.FutureContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFutureContractByID indicates an expected call of SelectFutureContractByID.
func (mr *MockBasicRepoMockRecorder) SelectFutureContractByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFutureContractByID", reflect.TypeOf((*MockBasicRepo)(nil).SelectFutureContractByID), ctx, id)
}

// SelectFutureDetailByCode mocks base method.
func (m *MockBasicRepo) SelectFutureDetailByCode(ctx context.Context, code string) (*pb.FutureDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFutureDetailByCode", ctx, code)
	ret0, _ := ret[0].(*pb.FutureDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFutureDetailByCode indicates an expected call of SelectFutureDetailByCode.
func (mr *MockBasicRepoMockRecorder) SelectFutureDetailByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFutureDetailByCode", reflect.TypeOf((*MockBasicRepo)(nil).SelectFutureDetailByCode), ctx, code)
}

// SelectOptionDetailByCode mocks base method.
func (m *MockBasicRepo) SelectOptionDetailByCode(ctx context.Context, code string) (*pb.OptionDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOptionDetailByCode", ctx, code)
	ret0, _ := ret[0].(*pb.OptionDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOptionDetailByCode indicates an expected call of SelectOptionDetailByCode.
func (mr *MockBasicRepoMockRecorder) SelectOptionDetailByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOptionDetailByCode", reflect.TypeOf((*MockBasicRepo)(nil).SelectOptionDetailByCode), ctx, code)
}

// SelectStockDetailByCode mocks base method.
func (m *MockBasicRepo) SelectStockDetailByCode(ctx context.Context, code string) (*pb.StockDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectStockDetailByCode", ctx, code)
	ret0, _ := ret[0].(*pb.StockDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectStockDetailByCode indicates an expected call of SelectStockDetailByCode.
func (mr *MockBasicRepoMockRecorder) SelectStockDetailByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectStockDetailByCode", reflect.TypeOf((*MockBasicRepo)(nil).SelectStockDetailByCode), ctx, code)
}

// UpdateFutureContract mocks base method.
func (m *MockBasicRepo) UpdateFutureContract(ctx context.Context, t *pb.FutureContract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFutureContract", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFutureContract indicates an expected call of UpdateFutureContract.
func (mr *MockBasicRepoMockRecorder) UpdateFutureContract(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFutureContract", reflect.TypeOf((*MockBasicRepo)(nil).UpdateFutureContract), ctx, t)
}

// UpdateFutureDetailContract mocks base method.
func (m *MockBasicRepo) UpdateFutureDetailContract(ctx context.Context, req *pb.UpdateFutureDetailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFutureDetailContract", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFutureDetailContract indicates an expected call of UpdateFutureDetailContract.
func (mr *MockBasicRepoMockRecorder) UpdateFutureDetailContract(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFutureDetailContract", reflect.TypeOf((*MockBasicRepo)(nil).UpdateFutureDetailContract), ctx, req)
}
