// Code generated by MockGen. DO NOT EDIT.
// Source: usecase_basic.go
//
// Generated by this command:
//
//	mockgen -source=usecase_basic.go -destination=./mocks/mocks_usecase_basic_test.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pb "github.com/chindada/panther/golang/pb"
	gomock "go.uber.org/mock/gomock"
)

// MockBasic is a mock of Basic interface.
type MockBasic struct {
	ctrl     *gomock.Controller
	recorder *MockBasicMockRecorder
	isgomock struct{}
}

// MockBasicMockRecorder is the mock recorder for MockBasic.
type MockBasicMockRecorder struct {
	mock *MockBasic
}

// NewMockBasic creates a new mock instance.
func NewMockBasic(ctrl *gomock.Controller) *MockBasic {
	mock := &MockBasic{ctrl: ctrl}
	mock.recorder = &MockBasicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasic) EXPECT() *MockBasicMockRecorder {
	return m.recorder
}

// GetAllFutureDetail mocks base method.
func (m *MockBasic) GetAllFutureDetail(ctx context.Context) ([]*pb.FutureDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFutureDetail", ctx)
	ret0, _ := ret[0].([]*pb.FutureDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFutureDetail indicates an expected call of GetAllFutureDetail.
func (mr *MockBasicMockRecorder) GetAllFutureDetail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFutureDetail", reflect.TypeOf((*MockBasic)(nil).GetAllFutureDetail), ctx)
}

// GetAllOptionDetail mocks base method.
func (m *MockBasic) GetAllOptionDetail(ctx context.Context) ([]*pb.OptionDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOptionDetail", ctx)
	ret0, _ := ret[0].([]*pb.OptionDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOptionDetail indicates an expected call of GetAllOptionDetail.
func (mr *MockBasicMockRecorder) GetAllOptionDetail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOptionDetail", reflect.TypeOf((*MockBasic)(nil).GetAllOptionDetail), ctx)
}

// GetAllStockDetail mocks base method.
func (m *MockBasic) GetAllStockDetail(ctx context.Context) ([]*pb.StockDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStockDetail", ctx)
	ret0, _ := ret[0].([]*pb.StockDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStockDetail indicates an expected call of GetAllStockDetail.
func (mr *MockBasicMockRecorder) GetAllStockDetail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStockDetail", reflect.TypeOf((*MockBasic)(nil).GetAllStockDetail), ctx)
}

// GetFutureKbar mocks base method.
func (m *MockBasic) GetFutureKbar(ctx context.Context, req *pb.HistoryKbarRequest) (*pb.HistoryKbarList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFutureKbar", ctx, req)
	ret0, _ := ret[0].(*pb.HistoryKbarList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFutureKbar indicates an expected call of GetFutureKbar.
func (mr *MockBasicMockRecorder) GetFutureKbar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFutureKbar", reflect.TypeOf((*MockBasic)(nil).GetFutureKbar), ctx, req)
}

// GetLastFutureKbar mocks base method.
func (m *MockBasic) GetLastFutureKbar(ctx context.Context, req *pb.HistoryKbarRequest) (*pb.HistoryKbarList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastFutureKbar", ctx, req)
	ret0, _ := ret[0].(*pb.HistoryKbarList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastFutureKbar indicates an expected call of GetLastFutureKbar.
func (mr *MockBasicMockRecorder) GetLastFutureKbar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastFutureKbar", reflect.TypeOf((*MockBasic)(nil).GetLastFutureKbar), ctx, req)
}

// GetTargetFuture mocks base method.
func (m *MockBasic) GetTargetFuture() []*pb.FutureDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetFuture")
	ret0, _ := ret[0].([]*pb.FutureDetail)
	return ret0
}

// GetTargetFuture indicates an expected call of GetTargetFuture.
func (mr *MockBasicMockRecorder) GetTargetFuture() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetFuture", reflect.TypeOf((*MockBasic)(nil).GetTargetFuture))
}

// GetTargetStock mocks base method.
func (m *MockBasic) GetTargetStock() []*pb.StockDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetStock")
	ret0, _ := ret[0].([]*pb.StockDetail)
	return ret0
}

// GetTargetStock indicates an expected call of GetTargetStock.
func (mr *MockBasicMockRecorder) GetTargetStock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetStock", reflect.TypeOf((*MockBasic)(nil).GetTargetStock))
}
