// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/capitan/v1/basic/futures": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic V1"
                ],
                "summary": "Get futures",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.FutureDetailList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/basic/options": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic V1"
                ],
                "summary": "Get options",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.OptionDetailList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/basic/stocks": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic V1"
                ],
                "summary": "Get stocks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.StockDetailList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/event/login": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event V1"
                ],
                "summary": "Get login events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.LoginEventList"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/event/shioaji": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event V1"
                ],
                "summary": "Get shioaji events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.ShioajiEventList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/logout": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/refresh": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/system/backup": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "List backup",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.BackupList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "Create backup",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "Restore backup",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.Backup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "Delete backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "backup-name",
                        "name": "backup-name",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/system/backup/download": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "Download backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "backup-name",
                        "name": "backup-name",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/system/backup/upload": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "Upload backup",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/system/info": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System V1"
                ],
                "summary": "Get system info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.SystemInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/trade/records": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade V1"
                ],
                "summary": "Get all trade records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.TradeList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade V1"
                ],
                "summary": "Get trade records by request",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade V1"
                ],
                "summary": "Get trade records by request",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.QueryTradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.TradeList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/user": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Update user except password",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "New user",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Delete user by username",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/user/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Get all user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.UserList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/capitan/v1/user/password": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Update user password",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pb.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "emptypb.Empty": {
            "type": "object"
        },
        "pb.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "response": {
                    "type": "string"
                }
            }
        },
        "pb.Backup": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "pb.BackupList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.Backup"
                    }
                }
            }
        },
        "pb.BasicUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/pb.UserRole"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "pb.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "pb.FutureDetail": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "day_trade": {
                    "type": "string"
                },
                "delivery_date": {
                    "type": "string"
                },
                "delivery_month": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "limit_down": {
                    "type": "number"
                },
                "limit_up": {
                    "type": "number"
                },
                "margin_trading_balance": {
                    "type": "integer"
                },
                "multiplier": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "option_right": {
                    "type": "string"
                },
                "reference": {
                    "type": "number"
                },
                "security_type": {
                    "type": "string"
                },
                "short_selling_balance": {
                    "type": "integer"
                },
                "strike_price": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "target_code": {
                    "type": "string"
                },
                "underlying_code": {
                    "type": "string"
                },
                "underlying_kind": {
                    "type": "string"
                },
                "unit": {
                    "type": "integer"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "pb.FutureDetailList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.FutureDetail"
                    }
                }
            }
        },
        "pb.LoginEvent": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "resp_code": {
                    "$ref": "#/definitions/pb.LoginRespCode"
                },
                "user": {
                    "$ref": "#/definitions/pb.User"
                }
            }
        },
        "pb.LoginEventList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.LoginEvent"
                    }
                }
            }
        },
        "pb.LoginRequest": {
            "type": "object",
            "properties": {
                "mfa_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "pb.LoginRespCode": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "LoginRespCode_OK",
                "LoginRespCode_PASSWORD_INCORRECT",
                "LoginRespCode_USER_NOT_FOUND",
                "LoginRespCode_DB_ERROR",
                "LoginRespCode_MFA_FAILED"
            ]
        },
        "pb.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "expire": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "pb.OptionDetail": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "day_trade": {
                    "type": "string"
                },
                "delivery_date": {
                    "type": "string"
                },
                "delivery_month": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "limit_down": {
                    "type": "number"
                },
                "limit_up": {
                    "type": "number"
                },
                "margin_trading_balance": {
                    "type": "integer"
                },
                "multiplier": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "option_right": {
                    "type": "string"
                },
                "reference": {
                    "type": "number"
                },
                "security_type": {
                    "type": "string"
                },
                "short_selling_balance": {
                    "type": "integer"
                },
                "strike_price": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "target_code": {
                    "type": "string"
                },
                "underlying_code": {
                    "type": "string"
                },
                "underlying_kind": {
                    "type": "string"
                },
                "unit": {
                    "type": "integer"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "pb.OptionDetailList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.OptionDetail"
                    }
                }
            }
        },
        "pb.OrderAction": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "OrderAction_ORDER_ACTION_UNKNOWN",
                "OrderAction_ORDER_ACTION_BUY",
                "OrderAction_ORDER_ACTION_SELL"
            ]
        },
        "pb.OrderStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8
            ],
            "x-enum-varnames": [
                "OrderStatus_ORDER_STATUS_UNKNOWN",
                "OrderStatus_ORDER_STATUS_CANCELLED",
                "OrderStatus_ORDER_STATUS_FILLED",
                "OrderStatus_ORDER_STATUS_PART_FILLED",
                "OrderStatus_ORDER_STATUS_INACTIVE",
                "OrderStatus_ORDER_STATUS_FAILED",
                "OrderStatus_ORDER_STATUS_PENDING_SUBMIT",
                "OrderStatus_ORDER_STATUS_PRE_SUBMITTED",
                "OrderStatus_ORDER_STATUS_SUBMITTED"
            ]
        },
        "pb.OrderType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "OrderType_TYPE_UNKNOWN",
                "OrderType_TYPE_STOCK_LOT",
                "OrderType_TYPE_STOCK_SHARE",
                "OrderType_TYPE_FUTURE",
                "OrderType_TYPE_OPTION"
            ]
        },
        "pb.QueryTradeRequest": {
            "type": "object",
            "properties": {
                "end_time": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "order_id": {
                    "type": "string"
                },
                "start_time": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        },
        "pb.ShioajiEvent": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "event": {
                    "type": "string"
                },
                "event_code": {
                    "type": "integer"
                },
                "info": {
                    "type": "string"
                },
                "resp_code": {
                    "type": "integer"
                }
            }
        },
        "pb.ShioajiEventList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.ShioajiEvent"
                    }
                }
            }
        },
        "pb.StockDetail": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "day_trade": {
                    "type": "string"
                },
                "delivery_date": {
                    "type": "string"
                },
                "delivery_month": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "limit_down": {
                    "type": "number"
                },
                "limit_up": {
                    "type": "number"
                },
                "margin_trading_balance": {
                    "type": "integer"
                },
                "multiplier": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "option_right": {
                    "type": "string"
                },
                "reference": {
                    "type": "number"
                },
                "security_type": {
                    "type": "string"
                },
                "short_selling_balance": {
                    "type": "integer"
                },
                "strike_price": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "target_code": {
                    "type": "string"
                },
                "underlying_code": {
                    "type": "string"
                },
                "underlying_kind": {
                    "type": "string"
                },
                "unit": {
                    "type": "integer"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "pb.StockDetailList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.StockDetail"
                    }
                }
            }
        },
        "pb.SystemBuild": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "pb.SystemInfo": {
            "type": "object",
            "properties": {
                "core": {
                    "$ref": "#/definitions/pb.SystemBuild"
                },
                "disk_usage": {
                    "type": "number"
                },
                "launch_time": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "web": {
                    "$ref": "#/definitions/pb.SystemBuild"
                }
            }
        },
        "pb.Trade": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/pb.OrderAction"
                },
                "code": {
                    "type": "string"
                },
                "filled_quantity": {
                    "type": "integer"
                },
                "future": {
                    "$ref": "#/definitions/pb.FutureDetail"
                },
                "option": {
                    "$ref": "#/definitions/pb.OptionDetail"
                },
                "order_id": {
                    "type": "string"
                },
                "order_time": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/pb.OrderStatus"
                },
                "stock": {
                    "$ref": "#/definitions/pb.StockDetail"
                },
                "type": {
                    "$ref": "#/definitions/pb.OrderType"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "pb.TradeList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.Trade"
                    }
                }
            }
        },
        "pb.User": {
            "type": "object",
            "properties": {
                "basic": {
                    "$ref": "#/definitions/pb.BasicUser"
                },
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "enable_totp": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "totp_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        },
        "pb.UserList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.User"
                    }
                }
            }
        },
        "pb.UserRole": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "UserRole_UNKNOWN",
                "UserRole_USER",
                "UserRole_ADMIN",
                "UserRole_ROOT"
            ]
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive.",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Capitan V1 OpenAPI",
	Description:      "Capitan V1 Srv's API docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
